### ISSUE TITLE
RV crashes

### ISSUE THREAD

**Issue by dessant** [kivy-garden/garden.recycleview#13]
@matham's suggestion was to do `view = viewclass()`, which worked.

``` python
Traceback (most recent call last):
   File "/home/vix/dev/prs/main/main.py", line 1004, in 
     MainApp().run()
   File "/home/vix/dev/prs/kivy/kivy/app.py", line 824, in run
     runTouchApp()
   File "/home/vix/dev/prs/kivy/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/vix/dev/prs/kivy/kivy/core/window/window_sdl2.py", line 600, in mainloop
     self._mainloop()
   File "/home/vix/dev/prs/kivy/kivy/core/window/window_sdl2.py", line 355, in _mainloop
     EventLoop.idle()
   File "/home/vix/dev/prs/kivy/kivy/base.py", line 336, in idle
     Clock.tick_draw()
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 490, in tick_draw
     self._process_events_before_frame()
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 640, in _process_events_before_frame
     event.tick(self._last_tick, remove)
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/home/vix/dev/prs/main/libs/garden/garden.recycleview/recycleview.py", line 655, in refresh_views
     lm.compute_visible_views()
   File "/home/vix/dev/prs/main/libs/garden/garden.recycleview/recycleview.py", line 512, in compute_visible_views
     new, old = recycleview.get_views(at_idx(px_start), at_idx(px_end))
   File "/home/vix/dev/prs/main/libs/garden/garden.recycleview/recycleview.py", line 678, in get_views
     return self.adapter.get_views(i_start, i_end)
   File "/home/vix/dev/prs/main/libs/garden/garden.recycleview/recycleview.py", line 313, in get_views
     view = get_view(index)
   File "/home/vix/dev/prs/main/libs/garden/garden.recycleview/recycleview.py", line 229, in get_view
     view = self.create_view(index, viewclass)
   File "/home/vix/dev/prs/main/libs/garden/garden.recycleview/recycleview.py", line 184, in create_view
     view = viewclass(**item)
   File "/home/vix/dev/prs/main/main.py", line 190, in __init__
     super().__init__(*args, **kwargs)
   File "/home/vix/dev/prs/kivy/kivy/uix/behaviors.py", line 151, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "/home/vix/dev/prs/kivy/kivy/uix/boxlayout.py", line 102, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/vix/dev/prs/kivy/kivy/uix/layout.py", line 67, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/vix/dev/prs/kivy/kivy/uix/widget.py", line 310, in __init__
     super(Widget, self).__init__(**kwargs)
   File "_event.pyx", line 253, in kivy._event.EventDispatcher.__init__ (kivy/_event.c:4566)
 TypeError: object.__init__() takes no parameters
```

**Comment by matham** [comment]
Already fixed in master.
