### ISSUE TITLE
App crashes when appending a new item to an empty RecycleView.data

### ISSUE THREAD

**Issue by Cheaterman** [kivy-garden/garden.recycleview#15]
https://bpaste.net/show/f18a5d4f7106
https://bpaste.net/show/e526ef72436d

Ka-boom!

**Comment by Cheaterman** [comment]
Traceback (most recent call last):
   File "main.py", line 40, in <module>
     Bug().run()
   File "/usr/lib64/python2.7/site-packages/kivy/app.py", line 825, in run
     runTouchApp()
   File "/usr/lib64/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib64/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 606, in mainloop
     self._mainloop()
   File "/usr/lib64/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 361, in _mainloop
     EventLoop.idle()
   File "/usr/lib64/python2.7/site-packages/kivy/base.py", line 336, in idle
     Clock.tick_draw()
   File "/usr/lib64/python2.7/site-packages/kivy/clock.py", line 490, in tick_draw
     self._process_events_before_frame()
   File "/usr/lib64/python2.7/site-packages/kivy/clock.py", line 640, in _process_events_before_frame
     event.tick(self._last_tick, remove)
   File "/usr/lib64/python2.7/site-packages/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/home/cheaterman/Dev/TMSApp/bug/recycleview/recycleview.py", line 650, in refresh_views
     lm.compute_positions_and_sizes(append)
   File "/home/cheaterman/Dev/TMSApp/bug/recycleview/recycleview.py", line 456, in compute_positions_and_sizes
     self._compute_positions(sizes[n:], pos[-1] + sizes[n - 1]))
 IndexError: list index out of range

**Comment by Cheaterman** [comment]
pos is [], pos[-1] goes boom boom?

**Comment by dessant** [comment]
Here is an example that runs:

``` python
from kivy.app import App
from kivy.lang import Builder
from kivy.garden.recycleview import RecycleView


kv = """
<Row@BoxLayout>:
    text: ''
    Label:
        text: root.text


GridLayout:
    rv: rv
    cols: 1
    Button:
        size_hint_y: None
        height: 48
        text: 'ADD'
        on_press: rv.data.append({'text': '2'})
    RecycleView:
        id: rv
        viewclass: 'Row'
        # data: [{'text': '1'}]
"""


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)

if __name__ == '__main__':
    TestApp().run()

```

``` python
 Traceback (most recent call last):
   File "<string>", line 48, in <module>
   File "/home/vix/dev/prs/kivy/kivy/app.py", line 825, in run
     runTouchApp()
   File "/home/vix/dev/prs/kivy/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/vix/dev/prs/kivy/kivy/core/window/window_sdl2.py", line 606, in mainloop
     self._mainloop()
   File "/home/vix/dev/prs/kivy/kivy/core/window/window_sdl2.py", line 361, in _mainloop
     EventLoop.idle()
   File "/home/vix/dev/prs/kivy/kivy/base.py", line 336, in idle
     Clock.tick_draw()
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 490, in tick_draw
     self._process_events_before_frame()
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 640, in _process_events_before_frame
     event.tick(self._last_tick, remove)
   File "/home/vix/dev/prs/kivy/kivy/clock.py", line 374, in tick
     ret = callback(self._dt)
   File "/home/vix/dev/prs/main/libs/garden/garden.recycleview/recycleview.py", line 650, in refresh_views
     lm.compute_positions_and_sizes(append)
   File "/home/vix/dev/prs/main/libs/garden/garden.recycleview/recycleview.py", line 456, in compute_positions_and_sizes
     self._compute_positions(sizes[n:], pos[-1] + sizes[n - 1]))
 IndexError: list index out of range
```

**Comment by dessant** [comment]
Fixed in https://github.com/kivy-garden/garden.recycleview/pull/17.
